# Generated by Django 3.1.1 on 2020-10-16 12:11

from django.db import migrations, models
import scriptTools.timeTools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInfo',
            fields=[
                ('resume_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('resume_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('resume_school', models.CharField(blank=True, default='', max_length=254)),
                ('resume_name', models.CharField(blank=True, default='', max_length=254)),
                ('resume_tele', models.CharField(max_length=254, unique=True)),
                ('resume_email', models.CharField(blank=True, default='', max_length=254)),
                ('resume_sex', models.CharField(blank=True, default='', max_length=254)),
                ('resume_highest_degree', models.CharField(blank=True, default='', max_length=254)),
                ('resume_location', models.CharField(blank=True, default='', max_length=254)),
                ('resume_late_major', models.CharField(blank=True, default='', max_length=254)),
                ('resume_expected_arrival_time', models.CharField(blank=True, default='', max_length=254)),
                ('resume_graduation_date', models.CharField(blank=True, default='', max_length=254)),
                ('resume_birthday', models.CharField(blank=True, default='', max_length=254)),
                ('resume_skill', models.CharField(blank=True, default='', max_length=2000)),
                ('resume_award', models.CharField(blank=True, default='', max_length=2000)),
                ('resume_project_experience', models.CharField(blank=True, default='', max_length=2000)),
                ('resume_self_description', models.CharField(blank=True, default='', max_length=2000)),
                ('resume_internship', models.CharField(blank=True, default='', max_length=2000)),
                ('resume_job_intension', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('user_tele', models.CharField(max_length=254, unique=True)),
                ('user_pwd', models.CharField(blank=True, default='', max_length=254)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('create_time', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobInfo',
            fields=[
                ('user_job_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('job_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('deliver_status', models.CharField(blank=True, default='申请中', max_length=254)),
            ],
            options={
                'unique_together': {('user_uuid', 'job_uuid')},
            },
        ),
    ]
