# Generated by Django 3.1.1 on 2020-10-16 12:11

from django.db import migrations, models
import scriptTools.timeTools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('job_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, default='', max_length=254)),
                ('job_category', models.CharField(blank=True, default='', max_length=254)),
                ('min_education', models.CharField(blank=True, default='', max_length=254)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('job_describe', models.CharField(blank=True, default='', max_length=2000)),
                ('company_name', models.CharField(blank=True, default='', max_length=254)),
                ('job_demand', models.CharField(blank=True, default='', max_length=2000)),
                ('company_tele', models.CharField(blank=True, default='', max_length=254)),
                ('company_email', models.CharField(blank=True, default='', max_length=254)),
                ('company_contact_name', models.CharField(blank=True, default='', max_length=254)),
                ('job_uuid', models.CharField(blank=True, default='', max_length=254)),
                ('job_create_time', models.CharField(blank=True, default=scriptTools.timeTools.dateStdTime, max_length=254)),
                ('job_end_time', models.CharField(blank=True, default='', max_length=254)),
                ('job_status', models.CharField(blank=True, default='进行中', max_length=254)),
            ],
        ),
    ]
